services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: travel_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -h localhost -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - rp-network
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: ta_redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - rp-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: travel-app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - rp-network
    volumes:
      - .:/app

volumes:
  db_data:
    name: my_db_data_volume
  redis_data:
    name: redis_data_volume
  export_data:
    name: export_data_volume
    external: true

networks:
  rp-network:
    driver: bridge
