"""empty message

Revision ID: 00002
Revises: 00001
Create Date: 2026-04-12 14:25:43.685983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00002'
down_revision: Union[str, None] = '00001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('places', sa.Column('latitude', sa.String(), nullable=False))
    op.alter_column('places', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('places', 'location')
    op.drop_column('projects', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('places', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('places', 'latitude')
    op.drop_column('places', 'longitude')
    # ### end Alembic commands ###
