"""empty message

Revision ID: 00003
Revises: 00002
Create Date: 2026-04-12 18:00:53.140460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00003'
down_revision: Union[str, None] = '00002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'places',
        'longitude',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="longitude::double precision"
    )

    op.alter_column(
        'places',
        'latitude',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="latitude::double precision"
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'latitude',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('places', 'longitude',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
